version: "3.9"

services:
  db:
    image: postgres:15
    container_name: tricount-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tricount
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: tricount-backend
    depends_on:
      - db
    environment:
      DATABASE_USER: postgres
      DATABASE_PW: postgres
      DATABASE_NAME: tricount
      JWT_SECRET_KEY: supersecret
      JWT_ALGORITHM: HS256
      JWT_EXPIRATION_MINUTES: 30
      LOG_FORMAT: "%(levelname)s | %(message)s"
      BASE_LOGGER_NAME: tricount
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: tricount-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    # volumes:
    #   - ./frontend:/app
    # command: npm start

volumes:
  postgres_data: